export {
  CHEAPEST_FILL_CAP,
  DEFAULT_MAX_PERPENDICULAR_METERS,
  DEFAULT_REMAINING_FRACTION,
  DEFAULT_TANK_LITRES,
  FILL_HASSLE_PENCE,
  MIN_FILL_SAVING_PENCE,
  litresToFill,
  pencePerKmFromConsumption,
  rankCheapestFill,
  type FillCandidate,
  type RankCheapestFillInput,
  type RankCheapestFillResult,
  type RankedFill,
} from "./rank.js";
