#!/usr/bin/env node
/**
 * Keep dotenv and Wrangler .dev.vars in lockstep for one explicit environment.
 * Usage: node scripts/with-env.mjs <dev|staging|prod> -- node scripts/env-sync.mjs [--check] [--from env|dev.vars]
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ENV_TARGETS,
  envExamplePaths,
  envPaths,
  isViteKey,
  loadEnvFile,
  mergeEnvMaps,
  pickKeys,
  serializeEnv,
} from "./env-file.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const HEADER = "# Generated by env:sync. Do not commit.";

function fail(message) {
  console.error(message);
  process.exit(1);
}

function parseArgs(argv) {
  let from = null;
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--check") {
      check = true;
      continue;
    }
    if (arg === "--from") {
      from = argv[i + 1] ?? null;
      i += 1;
      continue;
    }
    if (arg.startsWith("--from=")) {
      from = arg.slice("--from=".length);
    }
  }
  return { from, check };
}

function sameMap(a, b) {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const key of keys) {
    if ((a[key] ?? "") !== (b[key] ?? "")) return false;
  }
  return true;
}

function main() {
  const envName = process.env.BRIM_ENV;
  if (!envName || !ENV_TARGETS.includes(envName)) {
    fail(
      "Run via with-env.mjs so the target environment is explicit.\nUsage: node scripts/with-env.mjs <dev|staging|prod> -- node scripts/env-sync.mjs [--check] [--from env|dev.vars]",
    );
  }

  const { from, check } = parseArgs(process.argv.slice(2));
  if (from && from !== "env" && from !== "dev.vars") {
    fail("--from must be env or dev.vars");
  }

  const rel = envPaths(envName);
  const dotenvPath = path.join(root, rel.dotenv);
  const wranglerPath = path.join(root, rel.wrangler);
  const webPath = path.join(root, rel.web);

  const dotenv = loadEnvFile(dotenvPath);
  const wrangler = loadEnvFile(wranglerPath);
  const web = loadEnvFile(webPath);

  const examples = envExamplePaths(envName);
  if (!dotenv && !wrangler && !web) {
    fail(
      `No env files found for ${envName}.\nRun npm run env:setup, or copy ${examples.dotenv} → ${rel.dotenv} and ${examples.wrangler} → ${rel.wrangler}, then re-run.`,
    );
  }

  let merged;
  if (from === "env") {
    if (!dotenv) fail(`${rel.dotenv} is missing; cannot use --from env`);
    merged = { ...web, ...wrangler, ...dotenv };
  } else if (from === "dev.vars") {
    if (!wrangler) fail(`${rel.wrangler} is missing; cannot use --from dev.vars`);
    merged = { ...web, ...dotenv, ...wrangler };
  } else {
    const result = mergeEnvMaps([dotenv, wrangler, web]);
    if (result.conflicts.length > 0) {
      fail(
        `env:sync: ${envName} files disagree on: ${result.conflicts.join(", ")}\nRe-run with --from env or --from dev.vars to pick a winner.`,
      );
    }
    merged = result.merged;
  }

  const workerVars = pickKeys(merged, (key) => !isViteKey(key));
  const viteVars = pickKeys(merged, isViteKey);

  const nextDotenv = { ...workerVars, ...viteVars };
  const nextWrangler = workerVars;
  const nextWeb = viteVars;

  const drift = [];
  if (!sameMap(dotenv ?? {}, nextDotenv)) drift.push(rel.dotenv);
  if (!sameMap(wrangler ?? {}, nextWrangler)) drift.push(rel.wrangler);
  if (Object.keys(nextWeb).length > 0 && !sameMap(web ?? {}, nextWeb)) drift.push(rel.web);

  if (check) {
    if (drift.length > 0) {
      fail(`env:sync --check: drift in ${drift.join(", ")}`);
    }
    console.log(`env:sync: ${envName} files already match`);
    return;
  }

  mkdirSync(path.dirname(wranglerPath), { recursive: true });
  writeFileSync(dotenvPath, serializeEnv(nextDotenv, HEADER));
  writeFileSync(wranglerPath, serializeEnv(nextWrangler, HEADER));
  if (Object.keys(nextWeb).length > 0) {
    mkdirSync(path.dirname(webPath), { recursive: true });
    writeFileSync(webPath, serializeEnv(nextWeb, HEADER));
  }

  console.log(`env:sync: wrote ${rel.dotenv} ↔ ${rel.wrangler}${Object.keys(nextWeb).length > 0 ? ` and ${rel.web}` : ""} (${envName})`);
}

main();
